# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'harrierUI.ui'
#
# Created: Tue Mar 22 15:16:13 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 901)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -3, 492, 835))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.ConnectButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.ConnectButton.setObjectName("ConnectButton")
        self.gridLayout.addWidget(self.ConnectButton, 0, 1, 1, 1)
        self.UpdateButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.UpdateButton.setObjectName("UpdateButton")
        self.gridLayout.addWidget(self.UpdateButton, 1, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.KFactorField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.KFactorField.setText("")
        self.KFactorField.setObjectName("KFactorField")
        self.gridLayout_3.addWidget(self.KFactorField, 8, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 20, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 12, 0, 1, 1)
        self.LowPressureTriggerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LowPressureTriggerField.setText("")
        self.LowPressureTriggerField.setObjectName("LowPressureTriggerField")
        self.gridLayout_3.addWidget(self.LowPressureTriggerField, 17, 1, 1, 1)
        self.LowBatteryTriggerSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.LowBatteryTriggerSpinBox.setKeyboardTracking(False)
        self.LowBatteryTriggerSpinBox.setMaximum(99999)
        self.LowBatteryTriggerSpinBox.setObjectName("LowBatteryTriggerSpinBox")
        self.gridLayout_3.addWidget(self.LowBatteryTriggerSpinBox, 19, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 16, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 19, 0, 1, 1)
        self.LowPressureTriggerSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.LowPressureTriggerSpinBox.setKeyboardTracking(False)
        self.LowPressureTriggerSpinBox.setMaximum(99999)
        self.LowPressureTriggerSpinBox.setObjectName("LowPressureTriggerSpinBox")
        self.gridLayout_3.addWidget(self.LowPressureTriggerSpinBox, 17, 2, 1, 1)
        self.MeteringModeField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.MeteringModeField.setText("")
        self.MeteringModeField.setObjectName("MeteringModeField")
        self.gridLayout_3.addWidget(self.MeteringModeField, 4, 1, 1, 1)
        self.PumpStatusButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.PumpStatusButton.setObjectName("PumpStatusButton")
        self.gridLayout_3.addWidget(self.PumpStatusButton, 2, 2, 1, 1)
        self.HighPressureTriggerSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.HighPressureTriggerSpinBox.setKeyboardTracking(False)
        self.HighPressureTriggerSpinBox.setMaximum(99999)
        self.HighPressureTriggerSpinBox.setObjectName("HighPressureTriggerSpinBox")
        self.gridLayout_3.addWidget(self.HighPressureTriggerSpinBox, 16, 2, 1, 1)
        self.SlaveIDField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.SlaveIDField.setObjectName("SlaveIDField")
        self.gridLayout_3.addWidget(self.SlaveIDField, 1, 1, 1, 1)
        self.FlowRateSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.FlowRateSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.FlowRateSpinBox.setKeyboardTracking(False)
        self.FlowRateSpinBox.setMaximum(99999)
        self.FlowRateSpinBox.setObjectName("FlowRateSpinBox")
        self.gridLayout_3.addWidget(self.FlowRateSpinBox, 5, 2, 1, 1)
        self.AlarmActiveField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.AlarmActiveField.setText("")
        self.AlarmActiveField.setObjectName("AlarmActiveField")
        self.gridLayout_3.addWidget(self.AlarmActiveField, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.LowBatteryTriggerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.LowBatteryTriggerField.setText("")
        self.LowBatteryTriggerField.setObjectName("LowBatteryTriggerField")
        self.gridLayout_3.addWidget(self.LowBatteryTriggerField, 19, 1, 1, 1)
        self.FlowRateField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.FlowRateField.setText("")
        self.FlowRateField.setObjectName("FlowRateField")
        self.gridLayout_3.addWidget(self.FlowRateField, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 15, 0, 1, 1)
        self.ComPortField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.ComPortField.setObjectName("ComPortField")
        self.gridLayout_3.addWidget(self.ComPortField, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 17, 0, 1, 1)
        self.StatusField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.StatusField.setText("")
        self.StatusField.setObjectName("StatusField")
        self.gridLayout_3.addWidget(self.StatusField, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 13, 0, 1, 1)
        self.BatteryVoltageField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.BatteryVoltageField.setText("")
        self.BatteryVoltageField.setObjectName("BatteryVoltageField")
        self.gridLayout_3.addWidget(self.BatteryVoltageField, 14, 1, 1, 1)
        self.PressureField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.PressureField.setText("")
        self.PressureField.setObjectName("PressureField")
        self.gridLayout_3.addWidget(self.PressureField, 15, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.HighPressureTriggerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.HighPressureTriggerField.setText("")
        self.HighPressureTriggerField.setObjectName("HighPressureTriggerField")
        self.gridLayout_3.addWidget(self.HighPressureTriggerField, 16, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 14, 0, 1, 1)
        self.MeteringModeSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.MeteringModeSelectBox.setObjectName("MeteringModeSelectBox")
        self.MeteringModeSelectBox.addItem("")
        self.MeteringModeSelectBox.addItem("")
        self.MeteringModeSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.MeteringModeSelectBox, 4, 2, 1, 1)
        self.GrandTotalizerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.GrandTotalizerField.setText("")
        self.GrandTotalizerField.setObjectName("GrandTotalizerField")
        self.gridLayout_3.addWidget(self.GrandTotalizerField, 13, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 24, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 22, 0, 1, 1)
        self.OnTimeEditBox = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.OnTimeEditBox.setKeyboardTracking(False)
        self.OnTimeEditBox.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.OnTimeEditBox.setTime(QtCore.QTime(0, 0, 0))
        self.OnTimeEditBox.setObjectName("OnTimeEditBox")
        self.gridLayout_3.addWidget(self.OnTimeEditBox, 9, 2, 1, 1)
        self.OnCyclesField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.OnCyclesField.setObjectName("OnCyclesField")
        self.gridLayout_3.addWidget(self.OnCyclesField, 6, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 11, 0, 1, 1)
        self.PowerSavingsField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.PowerSavingsField.setObjectName("PowerSavingsField")
        self.gridLayout_3.addWidget(self.PowerSavingsField, 24, 1, 1, 1)
        self.RemoteOffField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.RemoteOffField.setObjectName("RemoteOffField")
        self.gridLayout_3.addWidget(self.RemoteOffField, 22, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 23, 0, 1, 1)
        self.ResetTotalizerButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.ResetTotalizerButton.setObjectName("ResetTotalizerButton")
        self.gridLayout_3.addWidget(self.ResetTotalizerButton, 12, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 21, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 8, 0, 1, 1)
        self.OnTimeField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.OnTimeField.setObjectName("OnTimeField")
        self.gridLayout_3.addWidget(self.OnTimeField, 9, 1, 1, 1)
        self.Input1Field = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.Input1Field.setObjectName("Input1Field")
        self.gridLayout_3.addWidget(self.Input1Field, 20, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.OffTimeField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.OffTimeField.setObjectName("OffTimeField")
        self.gridLayout_3.addWidget(self.OffTimeField, 10, 1, 1, 1)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 9, 0, 1, 1)
        self.Input2Field = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.Input2Field.setObjectName("Input2Field")
        self.gridLayout_3.addWidget(self.Input2Field, 21, 1, 1, 1)
        self.OffTimeEditBox = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.OffTimeEditBox.setKeyboardTracking(False)
        self.OffTimeEditBox.setObjectName("OffTimeEditBox")
        self.gridLayout_3.addWidget(self.OffTimeEditBox, 10, 2, 1, 1)
        self.IntervalField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.IntervalField.setText("")
        self.IntervalField.setObjectName("IntervalField")
        self.gridLayout_3.addWidget(self.IntervalField, 7, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 7, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 10, 0, 1, 1)
        self.OnTimeoutEditBox = QtGui.QTimeEdit(self.scrollAreaWidgetContents)
        self.OnTimeoutEditBox.setKeyboardTracking(False)
        self.OnTimeoutEditBox.setObjectName("OnTimeoutEditBox")
        self.gridLayout_3.addWidget(self.OnTimeoutEditBox, 11, 2, 1, 1)
        self.RemoteOffSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.RemoteOffSelectBox.setObjectName("RemoteOffSelectBox")
        self.RemoteOffSelectBox.addItem("")
        self.RemoteOffSelectBox.addItem("")
        self.RemoteOffSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.RemoteOffSelectBox, 22, 2, 1, 1)
        self.UnitsField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.UnitsField.setObjectName("UnitsField")
        self.gridLayout_3.addWidget(self.UnitsField, 25, 1, 1, 1)
        self.KFactorSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.KFactorSpinBox.setKeyboardTracking(False)
        self.KFactorSpinBox.setMinimum(1)
        self.KFactorSpinBox.setMaximum(9999)
        self.KFactorSpinBox.setObjectName("KFactorSpinBox")
        self.gridLayout_3.addWidget(self.KFactorSpinBox, 8, 2, 1, 1)
        self.OnTimeoutField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.OnTimeoutField.setObjectName("OnTimeoutField")
        self.gridLayout_3.addWidget(self.OnTimeoutField, 11, 1, 1, 1)
        self.Input1SelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.Input1SelectBox.setObjectName("Input1SelectBox")
        self.Input1SelectBox.addItem("")
        self.Input1SelectBox.addItem("")
        self.Input1SelectBox.addItem("")
        self.gridLayout_3.addWidget(self.Input1SelectBox, 20, 2, 1, 1)
        self.PowerSavingsSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.PowerSavingsSelectBox.setObjectName("PowerSavingsSelectBox")
        self.PowerSavingsSelectBox.addItem("")
        self.PowerSavingsSelectBox.addItem("")
        self.PowerSavingsSelectBox.addItem("")
        self.PowerSavingsSelectBox.addItem("")
        self.PowerSavingsSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.PowerSavingsSelectBox, 24, 2, 1, 1)
        self.UnitsSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.UnitsSelectBox.setObjectName("UnitsSelectBox")
        self.UnitsSelectBox.addItem("")
        self.UnitsSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.UnitsSelectBox, 25, 2, 1, 1)
        self.Input2SelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.Input2SelectBox.setObjectName("Input2SelectBox")
        self.Input2SelectBox.addItem("")
        self.Input2SelectBox.addItem("")
        self.Input2SelectBox.addItem("")
        self.gridLayout_3.addWidget(self.Input2SelectBox, 21, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 25, 0, 1, 1)
        self.PressureSensitivityField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.PressureSensitivityField.setObjectName("PressureSensitivityField")
        self.gridLayout_3.addWidget(self.PressureSensitivityField, 28, 1, 1, 1)
        self.FirmwareVersionField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.FirmwareVersionField.setText("")
        self.FirmwareVersionField.setObjectName("FirmwareVersionField")
        self.gridLayout_3.addWidget(self.FirmwareVersionField, 23, 1, 1, 1)
        self.PressureOffsetField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.PressureOffsetField.setObjectName("PressureOffsetField")
        self.gridLayout_3.addWidget(self.PressureOffsetField, 26, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 26, 0, 1, 1)
        self.PressureOffsetSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.PressureOffsetSpinBox.setKeyboardTracking(False)
        self.PressureOffsetSpinBox.setMaximum(9999)
        self.PressureOffsetSpinBox.setObjectName("PressureOffsetSpinBox")
        self.gridLayout_3.addWidget(self.PressureOffsetSpinBox, 26, 2, 1, 1)
        self.PressureSensitivitySpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.PressureSensitivitySpinBox.setKeyboardTracking(False)
        self.PressureSensitivitySpinBox.setMaximum(9999)
        self.PressureSensitivitySpinBox.setObjectName("PressureSensitivitySpinBox")
        self.gridLayout_3.addWidget(self.PressureSensitivitySpinBox, 28, 2, 1, 1)
        self.IntervalSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.IntervalSelectBox.setObjectName("IntervalSelectBox")
        self.IntervalSelectBox.addItem("")
        self.IntervalSelectBox.addItem("")
        self.IntervalSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.IntervalSelectBox, 7, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 28, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 18, 0, 1, 1)
        self.PowerSaveOnTriggerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.PowerSaveOnTriggerField.setObjectName("PowerSaveOnTriggerField")
        self.gridLayout_3.addWidget(self.PowerSaveOnTriggerField, 18, 1, 1, 1)
        self.PowerSaveOnTriggerSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.PowerSaveOnTriggerSpinBox.setKeyboardTracking(False)
        self.PowerSaveOnTriggerSpinBox.setMaximum(99999)
        self.PowerSaveOnTriggerSpinBox.setObjectName("PowerSaveOnTriggerSpinBox")
        self.gridLayout_3.addWidget(self.PowerSaveOnTriggerSpinBox, 18, 2, 1, 1)
        self.label_58 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 29, 0, 1, 1)
        self.AlarmActionSelectBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.AlarmActionSelectBox.setObjectName("AlarmActionSelectBox")
        self.AlarmActionSelectBox.addItem("")
        self.AlarmActionSelectBox.addItem("")
        self.gridLayout_3.addWidget(self.AlarmActionSelectBox, 29, 2, 1, 1)
        self.AlarmActionField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.AlarmActionField.setObjectName("AlarmActionField")
        self.gridLayout_3.addWidget(self.AlarmActionField, 29, 1, 1, 1)
        self.TotalizerField = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.TotalizerField.setObjectName("TotalizerField")
        self.gridLayout_3.addWidget(self.TotalizerField, 12, 1, 1, 1)
        self.ClearAlarmButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.ClearAlarmButton.setObjectName("ClearAlarmButton")
        self.gridLayout_3.addWidget(self.ClearAlarmButton, 3, 2, 1, 1)
        self.OnCyclesSpinBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.OnCyclesSpinBox.setKeyboardTracking(False)
        self.OnCyclesSpinBox.setObjectName("OnCyclesSpinBox")
        self.gridLayout_3.addWidget(self.OnCyclesSpinBox, 6, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 739, 21))
        self.menubar.setObjectName("menubar")
        self.menuHarrier = QtGui.QMenu(self.menubar)
        self.menuHarrier.setObjectName("menuHarrier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHarrier.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.ConnectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.UpdateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Input 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Flow Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Totalizer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "High pressure Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Slave ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Battery Shutoff", None, QtGui.QApplication.UnicodeUTF8))
        self.PumpStatusButton.setText(QtGui.QApplication.translate("MainWindow", "Pump On", None, QtGui.QApplication.UnicodeUTF8))
        self.SlaveIDField.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Com Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Alarm Active", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.ComPortField.setText(QtGui.QApplication.translate("MainWindow", "COM1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Low Pressure Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Grand Totalizer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Metering Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Battery Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.MeteringModeSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.MeteringModeSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.MeteringModeSelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Power Savings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Remote Off", None, QtGui.QApplication.UnicodeUTF8))
        self.OnTimeEditBox.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "h:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "On Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Firmware Version", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetTotalizerButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Input 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "KFactor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "On Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "On Time", None, QtGui.QApplication.UnicodeUTF8))
        self.OffTimeEditBox.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "h:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Off Time", None, QtGui.QApplication.UnicodeUTF8))
        self.OnTimeoutEditBox.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "h:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoteOffSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoteOffSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Nor Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoteOffSelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Nor Open", None, QtGui.QApplication.UnicodeUTF8))
        self.Input1SelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.Input1SelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Nor Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.Input1SelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Nor Open", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerSavingsSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerSavingsSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Notify", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerSavingsSelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerSavingsSelectBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.PowerSavingsSelectBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitsSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "US", None, QtGui.QApplication.UnicodeUTF8))
        self.UnitsSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Metric", None, QtGui.QApplication.UnicodeUTF8))
        self.Input2SelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.Input2SelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Nor Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.Input2SelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Nor Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Units", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Pressure Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.IntervalSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.IntervalSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.IntervalSelectBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Long", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Pressure Sensitivity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Power Save On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "Alarm Action", None, QtGui.QApplication.UnicodeUTF8))
        self.AlarmActionSelectBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.AlarmActionSelectBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Notify", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearAlarmButton.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHarrier.setTitle(QtGui.QApplication.translate("MainWindow", "harrier", None, QtGui.QApplication.UnicodeUTF8))

