# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0124_auto_20160930_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='tank_level',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_low_alarm_percentage',
            field=models.IntegerField(default=-1),
        ),
    ]
