# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 00:16
from __future__ import unicode_literals

from django.db import migrations


def add_groups(apps, schema_editor):
    from django.contrib.auth.models import Group

    distributor_group = Group(name="Distributors")
    distributor_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0124_auto_20160930_1540'),
    ]

    operations = [
        migrations.RunPython(add_groups)
    ]
