# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0125_make_distributor_group_20161208_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suppress_unassigned_pumps',
            field=models.IntegerField(default=0),
        ),
    ]
