# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0125_auto_20161005_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='tank_low_alarm_percentage',
            new_name='tank_level_alarm_trigger',
        ),
    ]
