# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0126_auto_20161005_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='sensor_type',
            field=models.IntegerField(default=0),
        ),
    ]
