# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0126_userprofile_suppress_unassigned_pumps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='suppress_unassigned_pumps',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_unassigned_pumps',
            field=models.IntegerField(default=1),
        ),
    ]
