# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0127_pump_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='tank_level_alarm_trigger',
            new_name='tank_level_notify_trigger',
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_level_shutoff_trigger',
            field=models.IntegerField(default=-1),
        ),
    ]
