# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0128_alarmpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user_selectable',
            field=models.BooleanField(default=False),
        ),
    ]
