# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0128_auto_20161025_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='tank_level',
            new_name='tank_level',
        ),
        migrations.RenameField(
            model_name='pump',
            old_name='tank_level_notify_trigger',
            new_name='tank_level_notify_trigger',
        ),
        migrations.RenameField(
            model_name='pump',
            old_name='tank_level_shutoff_trigger',
            new_name='tank_level_shutoff_trigger',
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_level_volume',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_level_volume_max',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_volume_notify_trigger',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pump',
            name='tank_volume_shutoff_trigger',
            field=models.IntegerField(default=-1),
        ),
    ]
