# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0129_auto_20161027_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='tank_level_volume',
            field=models.IntegerField(default=0),
        ),
    ]
