# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0130_auto_20161027_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='tank_level_volume',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='tank_volume_notify_trigger',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='tank_volume_shutoff_trigger',
        ),
    ]
