# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0130_auto_20170110_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
