# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0131_auto_20161028_1556'),
        ('gracopumpapp', '0131_paymentaccount_balance'),
    ]

    operations = [
    ]
