# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0132_merge_20170126_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='tank_type',
            field=models.IntegerField(default=0),
        ),
    ]
