# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-26 14:26
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0133_pump_tank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='flow_verify_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pump',
            name='flow_verify_percentage',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pump',
            name='next_flow_to_level_check',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=None)))
    ]
