# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0136_pump_analog_input_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='raw_analog_in',
            field=models.IntegerField(default=-1),
        ),
    ]
