# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0137_pump_raw_analog_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='temperature',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='pump',
            name='temperature_control',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='temperature_setpoint',
            field=models.IntegerField(default=-999),
        ),
    ]
