# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-09-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0138_auto_20180905_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='motor_protection_settings',
            field=models.IntegerField(default=0),
        ),
    ]
