# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-01-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0139_pump_motor_protection_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='motor_current_mV',
            field=models.IntegerField(default=-1),
        ),
    ]
