# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0140_pump_motor_current_mv'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='multiwell_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='well_flow_rate_8',
            field=models.FloatField(default=0),
        ),
    ]
