# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-05 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0141_auto_20190903_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField(default=-1)),
                ('custom_point_name', models.CharField(default='', max_length=100)),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gracopumpapp.Pump')),
            ],
        ),
    ]
