# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0142_pointcustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='totalizer_grand_well_8',
            field=models.FloatField(default=0),
        ),
    ]
