# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0144_auto_20190916_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='notes_field',
            field=models.CharField(default='', max_length=200),
        ),
    ]
