# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0145_pump_notes_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='well_status',
            field=models.IntegerField(default=0),
        ),
    ]
