# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-12-30 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0146_pump_well_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='multiwell_enable',
            field=models.IntegerField(default=0),
        ),
    ]
