# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-02-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0147_auto_20191230_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='ain_flow_rate_low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='ain_mA_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pump',
            name='ain_mA_low',
            field=models.IntegerField(default=0),
        ),
    ]
