# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-02-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0148_auto_20200213_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='ain_flow_rate_high',
            field=models.FloatField(default=0),
        ),
    ]
