# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2020-03-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gracopumpapp', '0149_pump_ain_flow_rate_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='ain_flow_rate_high',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='pump',
            name='ain_flow_rate_low',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='pump',
            name='ain_mA_high',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='pump',
            name='ain_mA_low',
            field=models.IntegerField(default=-1),
        ),
    ]
